// ---- Localized strings for PebbleKit JS ----
//
// One block per language. Add/edit translations in one place per language.
// LANG_ORDER maps the numeric index sent from the watch to a language code.

var LANG_ORDER = [
  'en', 'fr', 'de', 'es', 'it', 'nl', 'tr', 'cz', 'pt', 'el', 'sv', 'pl', 'sk', 'vi', 'ro', 'ca', 'no', 'ru', 'et', 'eu', 'fi', 'da', 'lt', 'sl', 'hu', 'hr', 'ga', 'lv', 'sr', 'zh', 'id', 'uk', 'cy', 'gl', 'ja', 'ko', 'he'
];

var LANGUAGES = {
  en: {
    weather: {
      0: 'CLEAR',
      1: 'MOSTLY CLEAR',
      2: 'PARTLY CLOUDY',
      3: 'OVERCAST',
      45: 'FOGGY',
      48: 'FOGGY',
      51: 'DRIZZLE',
      53: 'DRIZZLE',
      55: 'DRIZZLE',
      56: 'FRZG DRIZZLE',
      57: 'FRZG DRIZZLE',
      61: 'LIGHT RAIN',
      63: 'RAIN',
      65: 'HEAVY RAIN',
      66: 'FREEZING RAIN',
      67: 'FREEZING RAIN',
      71: 'LIGHT SNOW',
      73: 'SNOW',
      75: 'HEAVY SNOW',
      77: 'SNOW GRAINS',
      80: 'SHOWERS',
      81: 'SHOWERS',
      82: 'HEAVY SHOWERS',
      85: 'SNOW SHOWERS',
      86: 'SNOW SHOWERS',
      95: 'THUNDERSTORM',
      96: 'HAIL STORM',
      99: 'HAIL STORM'
    },
    cardinals: ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW'],
    labels: {
      STEPS: 'STEPS',
      WEEK: 'WEEK',
      DAY: 'DAY',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  fr: {
    weather: {
      0: 'DÉGAGÉ',
      1: 'PLUTÔT DÉGAGÉ',
      2: 'PART. NUAGEUX',
      3: 'COUVERT',
      45: 'BROUILLARD',
      48: 'BROUILLARD',
      51: 'BRUINE',
      53: 'BRUINE',
      55: 'BRUINE',
      56: 'BRUINE VERGL.',
      57: 'BRUINE VERGL.',
      61: 'PLUIE LÉGÈRE',
      63: 'PLUIE',
      65: 'FORTE PLUIE',
      66: 'PLUIE VERGL.',
      67: 'PLUIE VERGL.',
      71: 'NEIGE LÉGÈRE',
      73: 'NEIGE',
      75: 'FORTE NEIGE',
      77: 'NEIGE EN GRAINS',
      80: 'AVERSES',
      81: 'AVERSES',
      82: 'FORTES AVERSES',
      85: 'AVERSES NEIGE',
      86: 'AVERSES NEIGE',
      95: 'ORAGE',
      96: 'ORAGE GRÊLE',
      99: 'ORAGE GRÊLE'
    },
    cardinals: ['N', 'NE', 'E', 'SE', 'S', 'SO', 'O', 'NO'],
    labels: {
      STEPS: 'PAS',
      WEEK: 'SEM',
      DAY: 'JOUR',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  de: {
    weather: {
      0: 'KLAR',
      1: 'MEIST KLAR',
      2: 'TEILW. BEWÖLKT',
      3: 'STARK BEWÖLKT',
      45: 'NEBEL',
      48: 'NEBEL',
      51: 'NIESELREGEN',
      53: 'NIESELREGEN',
      55: 'NIESELREGEN',
      56: 'GEF. NIESELREGEN',
      57: 'GEF. NIESELREGEN',
      61: 'LEICHTER REGEN',
      63: 'REGEN',
      65: 'STARKER REGEN',
      66: 'GEFRIERENDER REGEN',
      67: 'GEFRIERENDER REGEN',
      71: 'LEICHTER SCHNEE',
      73: 'SCHNEE',
      75: 'STARKER SCHNEE',
      77: 'SCHNEEGRIESEL',
      80: 'REGENSCHAUER',
      81: 'REGENSCHAUER',
      82: 'STARKE REGENSC.',
      85: 'SCHNEESCHAUER',
      86: 'SCHNEESCHAUER',
      95: 'GEWITTER',
      96: 'HAGELSTURM',
      99: 'HAGELSTURM'
    },
    cardinals: ['N', 'NO', 'O', 'SO', 'S', 'SW', 'W', 'NW'],
    labels: {
      STEPS: 'SCHRITTE',
      WEEK: 'W',
      DAY: 'TAG',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  es: {
    weather: {
      0: 'DESPEJADO',
      1: 'MAYORMENTE DESP.',
      2: 'PARCIALMENTE NUB.',
      3: 'NUBLADO',
      45: 'NIEBLA',
      48: 'NIEBLA',
      51: 'LLOVIZNA',
      53: 'LLOVIZNA',
      55: 'LLOVIZNA',
      56: 'LLOVIZNA HELADA',
      57: 'LLOVIZNA HELADA',
      61: 'LLUVIA LIGERA',
      63: 'LLUVIA',
      65: 'LLUVIA FUERTE',
      66: 'LLUVIA HELADA',
      67: 'LLUVIA HELADA',
      71: 'NIEVE LIGERA',
      73: 'NIEVE',
      75: 'NIEVE FUERTE',
      77: 'GRANOS DE NIEVE',
      80: 'CHUBASCOS',
      81: 'CHUBASCOS',
      82: 'CHUBASCOS FUERTES',
      85: 'CHUBASCOS NIEVE',
      86: 'CHUBASCOS NIEVE',
      95: 'TORMENTA',
      96: 'TORM. GRANIZO',
      99: 'TORM. GRANIZO'
    },
    cardinals: ['N', 'NE', 'E', 'SE', 'S', 'SO', 'O', 'NO'],
    labels: {
      STEPS: 'PASOS',
      WEEK: 'SEM',
      DAY: 'DÍA',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  it: {
    weather: {
      0: 'SERENO',
      1: 'QUASI SERENO',
      2: 'PARZ. NUVOLOSO',
      3: 'COPERTO',
      45: 'NEBBIA',
      48: 'NEBBIA',
      51: 'PIOGGERELLA',
      53: 'PIOGGERELLA',
      55: 'PIOGGERELLA',
      56: 'PIOGG. GELATA',
      57: 'PIOGG. GELATA',
      61: 'PIOGGIA DEBOLE',
      63: 'PIOGGIA',
      65: 'FORTE PIOGGIA',
      66: 'PIOGGIA GELATA',
      67: 'PIOGGIA GELATA',
      71: 'NEVE DEBOLE',
      73: 'NEVE',
      75: 'FORTE NEVE',
      77: 'NEVE GRANULOSA',
      80: 'ROVESCI',
      81: 'ROVESCI',
      82: 'FORTI ROVESCI',
      85: 'ROVESCI NEVOSI',
      86: 'ROVESCI NEVOSI',
      95: 'TEMPORALE',
      96: 'GRANDINE',
      99: 'GRANDINE'
    },
    cardinals: ['N', 'NE', 'E', 'SE', 'S', 'SO', 'O', 'NO'],
    labels: {
      STEPS: 'PASSI',
      WEEK: 'SETT',
      DAY: 'GIORNO',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  nl: {
    weather: {
      0: 'HELDER',
      1: 'VRIJ HELDER',
      2: 'LICHT BEWÖLKT',
      3: 'BEWÖLKT',
      45: 'MISTIG',
      48: 'MISTIG',
      51: 'MIEZEL',
      53: 'MIEZEL',
      55: 'MIEZEL',
      56: 'IJZEL',
      57: 'IJZEL',
      61: 'LICHTE REGEN',
      63: 'REGEN',
      65: 'ZWARE REGEN',
      66: 'IJZEL',
      67: 'IJZEL',
      71: 'LICHTE SNEEUW',
      73: 'SNEEUW',
      75: 'ZWARE SNEEUW',
      77: 'SNEEUWKORRELS',
      80: 'BUIEN',
      81: 'BUIEN',
      82: 'ZWARE BUIEN',
      85: 'SNEEUWBUIEN',
      86: 'SNEEUWBUIEN',
      95: 'ONWEER',
      96: 'HAGELBUIEN',
      99: 'HAGELBUIEN'
    },
    cardinals: ['N', 'NO', 'O', 'ZO', 'Z', 'ZW', 'W', 'NW'],
    labels: {
      STEPS: 'STAPPEN',
      WEEK: 'WK',
      DAY: 'DAG',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  tr: {
    weather: {
      0: 'AÇIK',
      1: 'ÇOĞUNLUKLA AÇIK',
      2: 'PARÇALI BULUTLU',
      3: 'KAPALI',
      45: 'SİSLİ',
      48: 'SİSLİ',
      51: 'ÇİSELEME',
      53: 'ÇİSELEME',
      55: 'ÇİSELEME',
      56: 'DONDURUCU ÇİSELEME',
      57: 'DONDURUCU ÇİSELEME',
      61: 'HAFİF YAĞMUR',
      63: 'YAĞMUR',
      65: 'ŞİDDETLİ YAĞMUR',
      66: 'DONDURUCU YAĞMUR',
      67: 'DONDURUCU YAĞMUR',
      71: 'HAFİF KAR',
      73: 'KAR',
      75: 'ŞİDDETLİ KAR',
      77: 'KAR TANELERİ',
      80: 'SAĞANAK',
      81: 'SAĞANAK',
      82: 'ŞİDDETLİ SAĞANAK',
      85: 'KAR SAĞANAĞI',
      86: 'KAR SAĞANAĞI',
      95: 'FIRTINA',
      96: 'DOLU',
      99: 'DOLU'
    },
    cardinals: ['K', 'KD', 'D', 'GD', 'G', 'GB', 'B', 'KB'],
    labels: {
      STEPS: 'ADIMLAR',
      WEEK: 'HF',
      DAY: 'GÜN',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  cz: {
    weather: {
      0: 'JASNO',
      1: 'SKORO JASNО',
      2: 'POLOJASNO',
      3: 'ZATAŽENO',
      45: 'MLHA',
      48: 'MLHA',
      51: 'MRHOLENÍ',
      53: 'MRHOLENÍ',
      55: 'MRHOLENÍ',
      56: 'MRZN. MRHOLENÍ',
      57: 'MRZN. MRHOLENÍ',
      61: 'SLABÝ DÉŠŤ',
      63: 'DÉŠŤ',
      65: 'SILNÝ DÉŠŤ',
      66: 'MRZNOUCÍ DÉŠŤ',
      67: 'MRZNOUCÍ DÉŠŤ',
      71: 'SLABÉ SNĚŽENÍ',
      73: 'SNĚŽENÍ',
      75: 'SILNÉ SNĚŽENÍ',
      77: 'SNĚHOVÁ ZRNA',
      80: 'PŘEHÁŇKY',
      81: 'PŘEHÁŇKY',
      82: 'SILNÉ PŘEHÁŇKY',
      85: 'SNĚHOVÉ PŘEHÁŇKY',
      86: 'SNĚHOVÉ PŘEHÁŇKY',
      95: 'BOUŘKA',
      96: 'KRUPOBITÍ',
      99: 'KRUPOBITÍ'
    },
    cardinals: ['S', 'SV', 'V', 'JV', 'J', 'JZ', 'Z', 'SZ'],
    labels: {
      STEPS: 'KROKY',
      WEEK: 'TÝD',
      DAY: 'DEN',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  pt: {
    weather: {
      0: 'LIMPO',
      1: 'M.TO LIMPO',
      2: 'PARCIAL. NUBLADO',
      3: 'ENCOBERTO',
      45: 'NEVOEIRO',
      48: 'NEVOEIRO',
      51: 'CHUVISCO',
      53: 'CHUVISCO',
      55: 'CHUVISCO',
      56: 'CHUVISCO GELADO',
      57: 'CHUVISCO GELADO',
      61: 'CHUVA FRACA',
      63: 'CHUVA',
      65: 'CHUVA FORTE',
      66: 'CHUVA GELADA',
      67: 'CHUVA GELADA',
      71: 'NEVE FRACA',
      73: 'NEVE',
      75: 'NEVE FORTE',
      77: 'NEVE EM GRÃOS',
      80: 'PANCADAS CHUVA',
      81: 'PANCADAS CHUVA',
      82: 'PANCADAS FORTES',
      85: 'PANCADAS NEVE',
      86: 'PANCADAS NEVE',
      95: 'TROVOADA',
      96: 'GRANIZO',
      99: 'GRANIZO'
    },
    cardinals: ['N', 'NE', 'L', 'SE', 'S', 'SO', 'O', 'NO'],
    labels: {
      STEPS: 'PASSOS',
      WEEK: 'SEM',
      DAY: 'DIA',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  el: {
    weather: {
      0: 'ΑΙΘΡΙΟΣ',
      1: 'ΣΧΕΔΟΝ ΑΙΘΡΙΟΣ',
      2: 'ΜΕΡΙΚΩΣ ΣΥΝΝΕΦΙΑΣΜΕΝΟΣ',
      3: 'ΝΕΦΕΛΩΔΗΣ',
      45: 'ΟΜΙΧΛΩΔΗΣ',
      48: 'ΟΜΙΧΛΩΔΗΣ',
      51: 'ΨΙΧΑΛΑ',
      53: 'ΨΙΧΑΛΑ',
      55: 'ΨΙΧΑΛΑ',
      56: 'ΠΑΓΩΜΕΝΗ ΨΙΧΑΛΑ',
      57: 'ΠΑΓΩΜΕΝΗ ΨΙΧΑΛΑ',
      61: 'ΑΣΘΕΝΗΣ ΒΡΟΧΗ',
      63: 'ΒΡΟΧΗ',
      65: 'ΙΣΧΥΡΗ ΒΡΟΧΗ',
      66: 'ΠΑΓΩΜΕΝΗ ΒΡΟΧΗ',
      67: 'ΠΑΓΩΜΕΝΗ ΒΡΟΧΗ',
      71: 'ΑΣΘΕΝΗΣ ΧΙΟΝΟΠΤΩΣΗ',
      73: 'ΧΙΟΝΟΠΤΩΣΗ',
      75: 'ΙΣΧΥΡΗ ΧΙΟΝΟΠΤΩΣΗ',
      77: 'ΧΙΟΝΟΚΟΚΚΟΙ',
      80: 'ΟΜΒΡΟΙ',
      81: 'ΟΜΒΡΟΙ',
      82: 'ΙΣΧΥΡΟΙ ΟΜΒΡΟΙ',
      85: 'ΧΙΟΝΟΧΑΛΑΖΟ',
      86: 'ΧΙΟΝΟΧΑΛΑΖΟ',
      95: 'ΚΑΤΑΙΓΙΔΑ',
      96: 'ΧΑΛΑΖΟΠΤΩΣΗ',
      99: 'ΧΑΛΑΖΟΠΤΩΣΗ'
    },
    cardinals: ['Β', 'ΒΑ', 'Α', 'ΝΑ', 'Ν', 'ΝΔ', 'Δ', 'ΒΔ'],
    labels: {
      STEPS: 'ΒΉΜΑΤΑ',
      WEEK: 'ΕΒΔ',
      DAY: 'ΗΜΈ',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  sv: {
    weather: {
      0: 'KLART',
      1: 'MEST KLART',
      2: 'HALVKLART',
      3: 'MUULIT',
      45: 'DIMMA',
      48: 'DIMMA',
      51: 'DUGGREGN',
      53: 'DUGGREGN',
      55: 'DUGGREGN',
      56: 'UNDERKYLT REGN',
      57: 'UNDERKYLT REGN',
      61: 'LÄTT REGN',
      63: 'REGN',
      65: 'KRAFTIGT REGN',
      66: 'UNDERKYLT REGN',
      67: 'UNDERKYLT REGN',
      71: 'LÄTT SNÖFALL',
      73: 'SNÖFALL',
      75: 'KRAFTIGT SNÖFALL',
      77: 'SNÖKORN',
      80: 'REGNSKURAR',
      81: 'REGNSKURAR',
      82: 'KRAFTIGA SKURAR',
      85: 'SNÖBYER',
      86: 'SNÖBYER',
      95: 'ÅSKA',
      96: 'HAGELSKURAR',
      99: 'HAGELSKURAR'
    },
    cardinals: ['N', 'NO', 'O', 'SO', 'S', 'SV', 'V', 'NV'],
    labels: {
      STEPS: 'STEG',
      WEEK: 'V',
      DAY: 'DAG',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  pl: {
    weather: {
      0: 'CZYSTO',
      1: 'PRZEWAŻNIE CZYSTO',
      2: 'CZĘŚCIOWO ZACHMURZONE',
      3: 'ZACHMURZONE',
      45: 'MGLISTO',
      48: 'MGLISTO',
      51: 'MŻAWKA',
      53: 'MŻAWKA',
      55: 'MŻAWKA',
      56: 'MARZNĄCA MŻAWKA',
      57: 'MARZNĄCA MŻAWKA',
      61: 'LEKKI DESZCZ',
      63: 'DESZCZ',
      65: 'SILNY DESZCZ',
      66: 'MARZNĄCY DESZCZ',
      67: 'MARZNĄCY DESZCZ',
      71: 'LEKKI ŚNIEG',
      73: 'ŚNIEG',
      75: 'SILNY ŚNIEG',
      77: 'ŚNIEG ZIARNISTY',
      80: 'PRZELOTNE OPADY',
      81: 'PRZELOTNE OPADY',
      82: 'ULEWA',
      85: 'PRZELOTNY ŚNIEG',
      86: 'PRZELOTNY ŚNIEG',
      95: 'BURZA',
      96: 'GRAD',
      99: 'GRAD'
    },
    cardinals: ['Pn', 'PnW', 'W', 'PdW', 'Pd', 'PdZ', 'Z', 'PnZ'],
    labels: {
      STEPS: 'KROKI',
      WEEK: 'TYDZ',
      DAY: 'DZIEŃ',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  sk: {
    weather: {
      0: 'JASNO',
      1: 'SKORO JASNО',
      2: 'POLOJASNO',
      3: 'ZATIAHNUTÉ',
      45: 'HMLA',
      48: 'HMLA',
      51: 'MRHOLENIE',
      53: 'MRHOLENIE',
      55: 'MRHOLENIE',
      56: 'MRZN. MRHOLENIE',
      57: 'MRZN. MRHOLENIE',
      61: 'SLABÝ DÁŽĎ',
      63: 'DÁŽĎ',
      65: 'SILNÝ DÁŽĎ',
      66: 'MRZNOUCI DÁŽĎ',
      67: 'MRZNOUCI DÁŽĎ',
      71: 'SLABÉ SNĚŽENIE',
      73: 'SNĚŽENIE',
      75: 'SILNÉ SNĚŽENIE',
      77: 'SNEHOVÉ ZRNÁ',
      80: 'PREHÁNKY',
      81: 'PREHÁNKY',
      82: 'SILNÉ PREHÁNKY',
      85: 'SNEHOVÉ PREHÁNKY',
      86: 'SNEHOVÉ PREHÁNKY',
      95: 'BÚRKA',
      96: 'KRUPOBITIE',
      99: 'KRUPOBITIE'
    },
    cardinals: ['S', 'SV', 'V', 'JV', 'J', 'JZ', 'Z', 'SZ'],
    labels: {
      STEPS: 'KROKY',
      WEEK: 'TÝŽ',
      DAY: 'DEŇ',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  vi: {
    weather: {
      0: 'TRỜI QUANG',
      1: 'QUANG MÂY',
      2: 'CÓ MÂY',
      3: 'NHIỀU MÂY',
      45: 'SƯƠNG MÙ',
      48: 'SƯƠNG MÙ',
      51: 'MƯA PHÙN',
      53: 'MƯA PHÙN',
      55: 'MƯA PHÙN',
      56: 'MƯA PHÙN LẠNH',
      57: 'MƯA PHÙN LẠNH',
      61: 'MƯA NHỎ',
      63: 'MƯA',
      65: 'MƯA LỚN',
      66: 'MƯA BĂNG',
      67: 'MƯA BĂNG',
      71: 'TUYẾT RƠI NHẸ',
      73: 'TUYẾT',
      75: 'TUYẾT RƠI LỚN',
      77: 'MƯA TUYẾT',
      80: 'MƯA RÀO',
      81: 'MƯA RÀO',
      82: 'MƯA RÀO LỚN',
      85: 'MƯA TUYẾT RÀO',
      86: 'MƯA TUYẾT RÀO',
      95: 'DÔNG',
      96: 'MƯA ĐÁ',
      99: 'MƯA ĐÁ'
    },
    cardinals: ['B', 'ĐB', 'Đ', 'ĐN', 'N', 'TN', 'T', 'TB'],
    labels: {
      STEPS: 'BƯỚC',
      WEEK: 'TUẦN',
      DAY: 'NGÀY',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  ro: {
    weather: {
      0: 'SENIN',
      1: 'PREA SENIN',
      2: 'PARȚIAL NOROS',
      3: 'NOROS',
      45: 'CEAȚĂ',
      48: 'CEAȚĂ',
      51: 'BURNIȚĂ',
      53: 'BURNIȚĂ',
      55: 'BURNIȚĂ',
      56: 'BURNIȚĂ ÎNGHEȚATĂ',
      57: 'BURNIȚĂ ÎNGHEȚATĂ',
      61: 'PLOAIE SLABĂ',
      63: 'PLOAIE',
      65: 'PLOAIE TORENȚIALĂ',
      66: 'PLOAIE ÎNGHEȚATĂ',
      67: 'PLOAIE ÎNGHEȚATĂ',
      71: 'NINSOARE SLABĂ',
      73: 'NINSOARE',
      75: 'NINSOARE PUTERNICĂ',
      77: 'GRĂUNȚE DE ZĂPADĂ',
      80: 'AVERSE',
      81: 'AVERSE',
      82: 'AVERSE PUTERNICE',
      85: 'AVERSE DE NINSOARE',
      86: 'AVERSE DE NINSOARE',
      95: 'FURTUNĂ',
      96: 'GRINDINĂ',
      99: 'GRINDINĂ'
    },
    cardinals: ['N', 'NE', 'E', 'SE', 'S', 'SV', 'V', 'NV'],
    labels: {
      STEPS: 'PAȘI',
      WEEK: 'SĂPT',
      DAY: 'ZI',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  ca: {
    weather: {
      0: 'CLAR',
      1: 'MAJORITÀ CLAR',
      2: 'PARCIALMENT NUBOL',
      3: 'COBERT',
      45: 'BOIRA',
      48: 'BOIRA',
      51: 'BOREIM',
      53: 'BOREIM',
      55: 'BOREIM',
      56: 'BORIM GELAT',
      57: 'BORIM GELAT',
      61: 'PLUJA FEBLE',
      63: 'PLUJA',
      65: 'PLUJA FORTA',
      66: 'PLUJA GELADA',
      67: 'PLUJA GELADA',
      71: 'NEU FEBLE',
      73: 'NEU',
      75: 'NEU FORTA',
      77: 'NEU GRANULADA',
      80: 'XFALUTS',
      81: 'XFALUTS',
      82: 'XFALUTS FORTS',
      85: 'XFALUTS DE NEU',
      86: 'XFALUTS DE NEU',
      95: 'TEMPESTA',
      96: 'PEPEDREGADA',
      99: 'PEPEDREGADA'
    },
    cardinals: ['N', 'NE', 'E', 'SE', 'S', 'SO', 'O', 'NO'],
    labels: {
      STEPS: 'PASSOS',
      WEEK: 'SETM',
      DAY: 'DIA',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  no: {
    weather: {
      0: 'KLART',
      1: 'MEST KLART',
      2: 'LETTESKYET',
      3: 'OVERSKYET',
      45: 'TÅKE',
      48: 'TÅKE',
      51: 'DYNREGN',
      53: 'DYNREGN',
      55: 'DYNREGN',
      56: 'FROSSEN YRYR',
      57: 'FROSSEN YRYR',
      61: 'LETT REGN',
      63: 'REGN',
      65: 'KRAFTIG REGN',
      66: 'UNDERKJØLT REGN',
      67: 'UNDERKJØLT REGN',
      71: 'LETT SNØ',
      73: 'SNØ',
      75: 'KRAFTIG SNØ',
      77: 'SNØKORN',
      80: 'REGNBYER',
      81: 'REGNBYER',
      82: 'KRAFTIGE BYER',
      85: 'SNØBYER',
      86: 'SNØBYER',
      95: 'TORDENVÆR',
      96: 'HAGEL',
      99: 'HAGEL'
    },
    cardinals: ['N', 'NØ', 'Ø', 'SØ', 'S', 'SV', 'V', 'NV'],
    labels: {
      STEPS: 'SKRITT',
      WEEK: 'UKE',
      DAY: 'DAG',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  ru: {
    weather: {
      0: 'ЯСНО',
      1: 'ПРЕИМ. ЯСНО',
      2: 'ПЕРЕМ. ОБЛАЧНОСТЬ',
      3: 'ПАСМУРНО',
      45: 'ТУМАН',
      48: 'ТУМАН',
      51: 'МОРОСЬ',
      53: 'МОРОСЬ',
      55: 'МОРОСЬ',
      56: 'ЛЕДЯНАЯ МОРОСЬ',
      57: 'ЛЕДЯНАЯ МОРОСЬ',
      61: 'НЕБОЛЬШОЙ ДОЖДЬ',
      63: 'ДОЖДЬ',
      65: 'СИЛЬНЫЙ ДОЖДЬ',
      66: 'ЛЕДЯНОЙ ДОЖДЬ',
      67: 'ЛЕДЯНОЙ ДОЖДЬ',
      71: 'НЕБОЛЬШОЙ СНЕГ',
      73: 'СНЕГ',
      75: 'СИЛЬНЫЙ СНЕГ',
      77: 'СНЕЖНЫЕ ЗЕРНА',
      80: 'ЛИВНИ',
      81: 'ЛИВНИ',
      82: 'СИЛЬНЫЕ ЛИВНИ',
      85: 'СНЕГОПАДЫ',
      86: 'СНЕГОПАДЫ',
      95: 'ГРОЗА',
      96: 'ГРАД',
      99: 'ГРАД'
    },
    cardinals: ['С', 'СВ', 'В', 'ЮВ', 'Ю', 'ЮЗ', 'З', 'СЗ'],
    labels: {
      STEPS: 'ШАГИ',
      WEEK: 'НЕД',
      DAY: 'ДЕН',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  et: {
    weather: {
      0: 'SELGE',
      1: 'PEAMISELT SELGE',
      2: 'VAHELDUV PILVISUS',
      3: 'PILVINE',
      45: 'UDUNE',
      48: 'UDUNE',
      51: 'UDUVÍHM',
      53: 'UDUVÍHM',
      55: 'UDUVÍHM',
      56: 'JÄÄUDUVÍHM',
      57: 'JÄÄUDUVÍHM',
      61: 'KERGE VIHM',
      63: 'VIHM',
      65: 'TUGEV VIHM',
      66: 'JÄÄVIHM',
      67: 'JÄÄVIHM',
      71: 'KERGE LUMI',
      73: 'LUMI',
      75: 'TUGEV LUMI',
      77: 'LUMEKRUUBID',
      80: 'HOOGVIHM',
      81: 'HOOGVIHM',
      82: 'TUGEV HOOGVIHM',
      85: 'HOOGLUMI',
      86: 'HOOGLUMI',
      95: 'ÄIKE',
      96: 'RAHE',
      99: 'RAHE'
    },
    cardinals: ['P', 'KA', 'I', 'KG', 'L', 'EL', 'L', 'LO'],
    labels: {
      STEPS: 'SAMMUD',
      WEEK: 'NÄD',
      DAY: 'PÄEV',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  eu: {
    weather: {
      0: 'GARBI',
      1: 'GEHIENBAT GARBI',
      2: 'HODEI KERTSUAK',
      3: 'ESTALIA',
      45: 'LAINOA',
      48: 'LAINOA',
      51: 'ZIRRIMINA',
      53: 'ZIRRIMINA',
      55: 'ZIRRIMINA',
      56: 'ZIRRIMINA IZOTUA',
      57: 'ZIRRIMINA IZOTUA',
      61: 'EURI ARINA',
      63: 'EURIA',
      65: 'EURI JASA',
      66: 'EURI IZOTUA',
      67: 'EURI IZOTUA',
      71: 'ELUR ARINA',
      73: 'ELURRA',
      75: 'ELUR JASA',
      77: 'ELUR-GRANULATUAK',
      80: 'EURI-JASAK',
      81: 'EURI-JASAK',
      82: 'EURI-JASA GOGORRA',
      85: 'ELUR-JASAK',
      86: 'ELUR-JASAK',
      95: 'EKRIETA',
      96: 'RABASSAIREA',
      99: 'RABASSAIREA'
    },
    cardinals: ['I', 'IP', 'E', 'HE', 'H', 'HM', 'M', 'IM'],
    labels: {
      STEPS: 'URRATSAK',
      WEEK: 'AST',
      DAY: 'EGUN',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  fi: {
    weather: {
      0: 'SELKEÄÄ',
      1: 'MELKO SELKEÄÄ',
      2: 'PUOLIPILVISTÄ',
      3: 'PILVISTÄ',
      45: 'USVAISTA',
      48: 'USVAISTA',
      51: 'TIHKUSADETTA',
      53: 'TIHKUSADETTA',
      55: 'TIHKUSADETTA',
      56: 'JÄÄTÄVÄÄ TIHKUA',
      57: 'JÄÄTÄVÄÄ TIHKUA',
      61: 'HEIKKOA SADETTA',
      63: 'SADETTA',
      65: 'VOIMAKASTA SADETTA',
      66: 'JÄÄTÄVÄÄ SADETTA',
      67: 'JÄÄTÄVÄÄ SADETTA',
      71: 'HEIKKOA LUMISADETTA',
      73: 'LUMISADETTA',
      75: 'VOIMAKASTA LUMISADETTA',
      77: 'LUMIJYVÄSIÄ',
      80: 'SADEKUUROJA',
      81: 'SADEKUUROJA',
      82: 'RANKKASATEITA',
      85: 'LUMIKUUROJA',
      86: 'LUMIKUUROJA',
      95: 'UKKOSTA',
      96: 'RAKEITA',
      99: 'RAKEITA'
    },
    cardinals: ['P', 'KO', 'I', 'KA', 'E', 'LO', 'L', 'LU'],
    labels: {
      STEPS: 'ASKELTA',
      WEEK: 'VK',
      DAY: 'PÄIVÄ',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  da: {
    weather: {
      0: 'KLART',
      1: 'MEST KLART',
      2: 'LETTESKYET',
      3: 'OVERSKYET',
      45: 'TÅGE',
      48: 'TÅGE',
      51: 'STØVREGN',
      53: 'STØVREGN',
      55: 'STØVREGN',
      56: 'ISSLAG',
      57: 'ISSLAG',
      61: 'LETVED',
      63: 'REGN',
      65: 'KRAFTIG REGN',
      66: 'ISSLAG',
      67: 'ISSLAG',
      71: 'LETSNE',
      73: 'SNE',
      75: 'KRAFTIG SNE',
      77: 'SNEKORN',
      80: 'BYER',
      81: 'BYER',
      82: 'KRAFTIGE BYER',
      85: 'SNEBYER',
      86: 'SNEBYER',
      95: 'TORDEN',
      96: 'HAGEL',
      99: 'HAGEL'
    },
    cardinals: ['N', 'NØ', 'Ø', 'SØ', 'S', 'SV', 'V', 'NV'],
    labels: {
      STEPS: 'TRIN',
      WEEK: 'UGE',
      DAY: 'DAG',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  lt: {
    weather: {
      0: 'GIEDRA',
      1: 'MAŽAITIKIMYBE',
      2: 'MAŽAITIKIMYBE',
      3: 'APSINIAUKĘ',
      45: 'RŪKAS',
      48: 'RŪKAS',
      51: 'KDRENA',
      53: 'KDRENA',
      55: 'KDRENA',
      56: 'LEDO KDRENA',
      57: 'LEDO KDRENA',
      61: 'LENGVAS LIETUS',
      63: 'LIETUS',
      65: 'STIPRUS LIETUS',
      66: 'LEDO LIETUS',
      67: 'LEDO LIETUS',
      71: 'LENGVAS SNIEGAS',
      73: 'SNIEGAS',
      75: 'STIPRUS SNIEGAS',
      77: 'SNIEGO KRUOPOS',
      80: 'LIŪTYS',
      81: 'LIŪTYS',
      82: 'STIPRIOS LIŪTYS',
      85: 'SNIEGO KRUOPOS',
      86: 'SNIEGO KRUOPOS',
      95: 'PERKŪNIJA',
      96: 'KRUŠA',
      99: 'KRUŠA'
    },
    cardinals: ['Š', 'ŠR', 'R', 'PR', 'P', 'PV', 'V', 'ŠV'],
    labels: {
      STEPS: 'ŽINGSNIAI',
      WEEK: 'SAV',
      DAY: 'PARA',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  sl: {
    weather: {
      0: 'JASNO',
      1: 'PRETEŽNO JASNO',
      2: 'DELNO OBLAČNO',
      3: 'OBLAČNO',
      45: 'MEGLA',
      48: 'MEGLA',
      51: 'PRŠENJE',
      53: 'PRŠENJE',
      55: 'PRŠENJE',
      56: 'LEDENO PRŠENJE',
      57: 'LEDENO PRŠENJE',
      61: 'RAHEL DEŽ',
      63: 'DEŽ',
      65: 'MOČAN DEŽ',
      66: 'LEDEN DEŽ',
      67: 'LEDEN DEŽ',
      71: 'RAHEL SNEG',
      73: 'SNEG',
      75: 'MOČAN SNEG',
      77: 'SNEŽNA ZRNA',
      80: 'PLOHA',
      81: 'PLOHA',
      82: 'MOČNA PLOHA',
      85: 'SNEŽNA PLOHA',
      86: 'SNEŽNA PLOHA',
      95: 'NEVIHTA',
      96: 'TOČA',
      99: 'TOČA'
    },
    cardinals: ['S', 'SV', 'V', 'JV', 'J', 'JZ', 'Z', 'SZ'],
    labels: {
      STEPS: 'KORAKI',
      WEEK: 'TED',
      DAY: 'DAN',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  hu: {
    weather: {
      0: 'TISZTA',
      1: 'RENSZINT TISZTA',
      2: 'RÉSZLEGESEN FELHŐS',
      3: 'BORULT',
      45: 'KÖDÖS',
      48: 'KÖDÖS',
      51: 'SZITÁLÁS',
      53: 'SZITÁLÁS',
      55: 'SZITÁLÁS',
      56: 'ÓNOS SZITÁLÁS',
      57: 'ÓNOS SZITÁLÁS',
      61: 'GYENGE ESŐ',
      63: 'ESŐ',
      65: 'ERŐS ESŐ',
      66: 'ÓNOS ESŐ',
      67: 'ÓNOS ESŐ',
      71: 'GYENGE HAVAZÁS',
      73: 'HAVAZÁS',
      75: 'ERŐS HAVAZÁS',
      77: 'HÓDARA',
      80: 'ZÁPOR',
      81: 'ZÁPOR',
      82: 'ERŐS ZÁPOR',
      85: 'HÓZÁPOR',
      86: 'HÓZÁPOR',
      95: 'VIHAR',
      96: 'JÉGESŐ',
      99: 'JÉGESŐ'
    },
    cardinals: ['É', 'ÉK', 'K', 'DK', 'D', 'DNY', 'NY', 'ÉNY'],
    labels: {
      STEPS: 'LÉPÉSEK',
      WEEK: 'HÉT',
      DAY: 'NAP',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  hr: {
    weather: {
      0: 'VEDRO',
      1: 'PRETEŽNO VEDRO',
      2: 'DJELOMIČNO OBLAČNO',
      3: 'OBLAČNO',
      45: 'MAGLA',
      48: 'MAGLA',
      51: 'SIPENJE',
      53: 'SIPENJE',
      55: 'SIPENJE',
      56: 'LEDENA ROSULJA',
      57: 'LEDENA ROSULJA',
      61: 'SLABA KIŠA',
      63: 'KIŠA',
      65: 'JAKA KIŠA',
      66: 'LEDENA KIŠA',
      67: 'LEDENA KIŠA',
      71: 'SLAB SNIJEG',
      73: 'SNIJEG',
      75: 'JAK SNIJEG',
      77: 'SNJEŽNA ZRNA',
      80: 'PLJUSKOVI',
      81: 'PLJUSKOVI',
      82: 'JAK PLJUSKOVI',
      85: 'SNJEŽNI PLJUSKOVI',
      86: 'SNJEŽNI PLJUSKOVI',
      95: 'GRMLJAVINA',
      96: 'GRAD',
      99: 'GRAD'
    },
    cardinals: ['S', 'SI', 'I', 'JI', 'J', 'JZ', 'Z', 'SZ'],
    labels: {
      STEPS: 'KORACI',
      WEEK: 'TJ',
      DAY: 'DAN',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  ga: {
    weather: {
      0: 'GLAN',
      1: 'PÁIRTEACH GLAN',
      2: 'PÁIRTEACH SCALTA',
      3: 'SCALTA',
      45: 'CEOCH',
      48: 'CEOCH',
      51: 'DRUCHLÁK',
      53: 'DRUCHLÁK',
      55: 'DRUCHLÁK',
      56: 'DRUCHLÁK REOITE',
      57: 'DRUCHLÁK REOITE',
      61: 'BÁISTEACH ÉADROM',
      63: 'BÁISTEACH',
      65: 'BÁISTEACH THROM',
      66: 'BÁISTEACH REOITE',
      67: 'BÁISTEACH REOITE',
      71: 'SNEACHTA ÉADROM',
      73: 'SNEACHTA',
      75: 'SNEACHTA TROM',
      77: 'GRÁINNÍ SNEACHTA',
      80: 'CITHEANNA',
      81: 'CITHEANNA',
      82: 'CITHEANNA TROMA',
      85: 'CITHEANNA SNEACHTA',
      86: 'CITHEANNA SNEACHTA',
      95: 'STOIRM THIURNACH',
      96: 'STOIRM CHLOCHSHNEA.',
      99: 'STOIRM CHLOCHSHNEA.'
    },
    cardinals: ['T', 'TO', 'O', 'DO', 'D', 'DI', 'I', 'TI'],
    labels: {
      STEPS: 'CÉIMEANNA',
      WEEK: 'SCHT',
      DAY: 'LÁ',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  lv: {
    weather: {
      0: 'SKAIDRS',
      1: 'GANDRĪZ SKAIDRS',
      2: 'DAĻĒJI MĀKOŅAINS',
      3: 'APMĀCIES',
      45: 'MIGLAINS',
      48: 'MIGLAINS',
      51: 'SMRIDZINĀŠANA',
      53: 'SMRIDZINĀŠANA',
      55: 'SMRIDZINĀŠANA',
      56: 'SALST SMRIDZIN.',
      57: 'SALST SMRIDZIN.',
      61: 'VIEGLS LIETUS',
      63: 'LIETUS',
      65: 'STIPRS LIETUS',
      66: 'SALST LIETUS',
      67: 'SALST LIETUS',
      71: 'VIEGLS SNIEGS',
      73: 'SNIEGS',
      75: 'STIPRS SNIEGS',
      77: 'SNIEGA GRAUDI',
      80: 'LIETUS GĀZES',
      81: 'LIETUS GĀZES',
      82: 'STIPRAS GĀZES',
      85: 'SNIEGA GĀZES',
      86: 'SNIEGA GĀZES',
      95: 'PĒRKONA NEGAISS',
      96: 'KRUŠA',
      99: 'KRUŠA'
    },
    cardinals: ['Z', 'ZA', 'A', 'DA', 'D', 'DR', 'R', 'ZR'],
    labels: {
      STEPS: 'SOĻI',
      WEEK: 'NED',
      DAY: 'DIENA',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  sr: {
    weather: {
      0: 'VEDRO',
      1: 'PRETEŽNO VEDRO',
      2: 'DELIMIČNO OBLAČNO',
      3: 'OBLAČNO',
      45: 'MAGLA',
      48: 'MAGLA',
      51: 'ROSULJA',
      53: 'ROSULJA',
      55: 'ROSULJA',
      56: 'LEDENA ROSULJA',
      57: 'LEDENA ROSULJA',
      61: 'SLABA KIŠA',
      63: 'KIŠA',
      65: 'JAKA KIŠA',
      66: 'LEDENA KIŠA',
      67: 'LEDENA KIŠA',
      71: 'SLAB SNIJEG',
      73: 'SNIJEG',
      75: 'JAK SNIJEG',
      77: 'SNEŽNA ZRNA',
      80: 'PLJUSKOVI',
      81: 'PLJUSKOVI',
      82: 'JAK PLJUSKOVI',
      85: 'SNJEŽNI PLJUSKOVI',
      86: 'SNJEŽNI PLJUSKOVI',
      95: 'GRMLJAVINA',
      96: 'GRAD',
      99: 'GRAD'
    },
    cardinals: ['S', 'SI', 'I', 'JI', 'J', 'JZ', 'Z', 'SZ'],
    labels: {
      STEPS: 'KORACI',
      WEEK: 'NED',
      DAY: 'DAN',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  zh: {
    weather: {
      0: '晴朗',
      1: '大部晴朗',
      2: '多云',
      3: '阴天',
      45: '雾',
      48: '雾',
      51: '毛毛雨',
      53: '毛毛雨',
      55: '毛毛雨',
      56: '冻毛毛雨',
      57: '冻毛毛雨',
      61: '小雨',
      63: '雨',
      65: '大雨',
      66: '冻雨',
      67: '冻雨',
      71: '小雪',
      73: '雪',
      75: '大雪',
      77: '雪米',
      80: '阵雨',
      81: '阵雨',
      82: '强阵雨',
      85: '阵雪',
      86: '阵雪',
      95: '雷暴',
      96: '冰雹',
      99: '冰雹'
    },
    cardinals: ['北', '东北', '东', '东南', '南', '西南', '西', '西北'],
    labels: {
      STEPS: '步数',
      WEEK: '周',
      DAY: '天',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  id: {
    weather: {
      0: 'CERAH',
      1: 'CERAH BERAWAN',
      2: 'BERAWAN SEBAGIAN',
      3: 'MENDUNG',
      45: 'BERKABUT',
      48: 'BERKABUT',
      51: 'GERIMIS',
      53: 'GERIMIS',
      55: 'GERIMIS',
      56: 'GERIMIS BEKU',
      57: 'GERIMIS BEKU',
      61: 'HUJAN RINGAN',
      63: 'HUJAN',
      65: 'HUJAN LEBAT',
      66: 'HUJAN BEKU',
      67: 'HUJAN BEKU',
      71: 'SALJU RINGAN',
      73: 'SALJU',
      75: 'SALJU LEBAT',
      77: 'BUTIRAN SALJU',
      80: 'HUJAN DERAS',
      81: 'HUJAN DERAS',
      82: 'HUJAN SANGAT DERAS',
      85: 'SALJU DERAS',
      86: 'SALJU DERAS',
      95: 'BADAI PETIR',
      96: 'HUJAN ES',
      99: 'HUJAN ES'
    },
    cardinals: ['U', 'TL', 'T', 'TG', 'S', 'BD', 'B', 'BL'],
    labels: {
      STEPS: 'LANGKAH',
      WEEK: 'MING',
      DAY: 'HARI',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  uk: {
    weather: {
      0: 'ЯСНО',
      1: 'ПЕРЕВАЖНО ЯСНО',
      2: 'МІНЛИВА ХМАРНІСТЬ',
      3: 'ПОХМУРО',
      45: 'ТУМАН',
      48: 'ТУМАН',
      51: 'МРЯКА',
      53: 'МРЯКА',
      55: 'МРЯКА',
      56: 'КРИЖАНА МРЯКА',
      57: 'КРИЖАНА МРЯКА',
      61: 'НЕВЕЛИКИЙ ДОЩ',
      63: 'ДОЩ',
      65: 'СИЛЬНИЙ ДОЩ',
      66: 'КРИЖАНИЙ ДОЩ',
      67: 'КРИЖАНИЙ ДОЩ',
      71: 'НЕВЕЛИКИЙ СНІГ',
      73: 'СНІГ',
      75: 'СИЛЬНИЙ СНІГ',
      77: 'СНІЖНА КРУПА',
      80: 'ЗЛИВИ',
      81: 'ЗЛИВИ',
      82: 'СИЛЬНІ ЗЛИВИ',
      85: 'СНІЖНІ ЗЛИВИ',
      86: 'СНІЖНІ ЗЛИВИ',
      95: 'ГРОЗА',
      96: 'ГРАД',
      99: 'ГРАД'
    },
    cardinals: ['Пн', 'ПнСх', 'Сх', 'ПдСх', 'Пд', 'ПдЗх', 'Зх', 'ПнЗх'],
    labels: {
      STEPS: 'КРОКИ',
      WEEK: 'ТИЖ',
      DAY: 'ДЕНЬ',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  cy: {
    weather: {
      0: 'CLIR',
      1: 'GAN EIRAF',
      2: 'RHANNOL GYMOGLOG',
      3: 'CYMOGLOG',
      45: 'NIWLOG',
      48: 'NIWLOG',
      51: 'YRYR',
      53: 'YRYR',
      55: 'YRYR',
      56: 'YRYR RHEWI',
      57: 'YRYR RHEWI',
      61: 'GLAW YSGAFN',
      63: 'GLAW',
      65: 'GLAW TRWM',
      66: 'GLAW RHEWI',
      67: 'GLAW RHEWI',
      71: 'EIRA YSGAFN',
      73: 'EIRA',
      75: 'EIRA TRWM',
      77: 'GRANNAU EIRA',
      80: 'CAWODDYDD',
      81: 'CAWODDYDD',
      82: 'CAWODDYDD TRWM',
      85: 'CAWODDYDD EIRA',
      86: 'CAWODDYDD EIRA',
      95: 'STORM THARANNAU',
      96: 'STORM CENLLYG',
      99: 'STORM CENLLYG'
    },
    cardinals: ['G', 'GDd', 'Dd', 'DD', 'D', 'DG', 'Gor', 'GG'],
    labels: {
      STEPS: 'CAMAU',
      WEEK: 'WNOS',
      DAY: 'DIWR',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  gl: {
    weather: {
      0: 'CLARO',
      1: 'MOI CLARO',
      2: 'PARCIALMENTE NUBRADO',
      3: 'NUBRADO',
      45: 'NÉBOA',
      48: 'NÉBOA',
      51: 'MOXÍN',
      53: 'MOXÍN',
      55: 'MOXÍN',
      56: 'MOXÍN XEADA',
      57: 'MOXÍN XEADA',
      61: 'CHOVIA MIÚDA',
      63: 'CHOVIA',
      65: 'CHOVIA FORTE',
      66: 'CHOVIA XEADA',
      67: 'CHOVIA XEADA',
      71: 'NEVE MIÚDA',
      73: 'NEVE',
      75: 'NEVE FORTE',
      77: 'NEVE GRANULADA',
      80: 'CHUBASCOS',
      81: 'CHUBASCOS',
      82: 'CHUBASCOS FORTES',
      85: 'CHUBASCOS DE NEVE',
      86: 'CHUBASCOS DE NEVE',
      95: 'TORMENTA',
      96: 'TORMENTA DE SARABIA',
      99: 'TORMENTA DE SARABIA'
    },
    cardinals: ['N', 'NE', 'L', 'SE', 'S', 'SO', 'O', 'NO'],
    labels: {
      STEPS: 'PASOS',
      WEEK: 'SEM',
      DAY: 'DÍA',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  ja: {
    weather: {
      0: '快晴',
      1: 'おおむね晴れ',
      2: '晴れ時々曇り',
      3: '曇り',
      45: '霧',
      48: '霧',
      51: '霧雨',
      53: '霧雨',
      55: '霧雨',
      56: '着氷性の霧雨',
      57: '着氷性の霧雨',
      61: '小雨',
      63: '雨',
      65: '大雨',
      66: '着氷性の雨',
      67: '着氷性の雨',
      71: '小雪',
      73: '雪',
      75: '大雪',
      77: 'あられ',
      80: 'にわか雨',
      81: 'にわか雨',
      82: '激しいにわか雨',
      85: 'にわか雪',
      86: 'にわか雪',
      95: '雷雨',
      96: '雹',
      99: '雹'
    },
    cardinals: ['北', '北東', '東', '南東', '南', '南西', '西', '北西'],
    labels: {
      STEPS: '歩数',
      WEEK: '週',
      DAY: '日',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  ko: {
    weather: {
      0: '맑음',
      1: '대체로 맑음',
      2: '구름 조금',
      3: '흐림',
      45: '안개',
      48: '안개',
      51: '이슬비',
      53: '이슬비',
      55: '이슬비',
      56: '얼어붙는 이슬비',
      57: '얼어붙는 이슬비',
      61: '약한 비',
      63: '비',
      65: '강한 비',
      66: '얼어붙는 비',
      67: '얼어붙는 비',
      71: '약한 눈',
      73: '눈',
      75: '강한 눈',
      77: '눈 알갱이',
      80: '소나기',
      81: '소나기',
      82: '강한 소나기',
      85: '가끔 눈',
      86: '가끔 눈',
      95: '뇌우',
      96: '우박',
      99: '우박'
    },
    cardinals: ['북', '북동', '동', '남동', '남', '남서', '서', '북서'],
    labels: {
      STEPS: '걸음',
      WEEK: '주',
      DAY: '일',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  },
  he: {
    weather: {
      0: 'בהיר',
      1: 'בהיר לרוב',
      2: 'מעונן חלקית',
      3: 'מעונן',
      45: 'ערפילי',
      48: 'ערפילי',
      51: 'רסס',
      53: 'רסס',
      55: 'רסס',
      56: 'רסס קופא',
      57: 'רסס קופא',
      61: 'גשם קל',
      63: 'גשם',
      65: 'גשם כבד',
      66: 'גשם קופא',
      67: 'גשם קופא',
      71: 'שלג קל',
      73: 'שלג',
      75: 'שלג כבד',
      77: 'פתיתי שלג',
      80: 'ממטרים',
      81: 'ממטרים',
      82: 'ממטרים כבדים',
      85: 'ממטרי שלג',
      86: 'ממטרי שלג',
      95: 'סופת רעמים',
      96: 'סופת ברד',
      99: 'סופת ברד'
    },
    cardinals: ['צ׳', 'צמ׳', 'מ׳', 'דמ׳', 'ד׳', 'דמ׳', 'מ׳', 'צמ׳'],
    labels: {
      STEPS: 'צעדים',
      WEEK: 'שב',
      DAY: 'יום',
      DIST_METRIC: 'KM',
      DIST_IMPERIAL: 'MI',
      WIND_METRIC: 'KM/H',
      WIND_IMPERIAL: 'MPH'
    }
  }
};

function getLang(idx) {
  var i = parseInt(idx) || 0;
  if (i < 0 || i >= LANG_ORDER.length) i = 0;
  return LANGUAGES[LANG_ORDER[i]] || LANGUAGES.en;
}

module.exports = {
  getLang: getLang,
  LANG_ORDER: LANG_ORDER,
  LANGUAGES: LANGUAGES
};
