#include "languages.h"
#include <pebble.h>

/* day names in many different languages! */
const char dayNames[38][7][8] = {
    {"SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"},
    {"DIM", "LUN", "MAR", "MER", "JEU", "VEN", "SAM"},
    {"SO", "MO", "DI", "MI", "DO", "FR", "SA"},
    {"DOM", "LUN", "MAR", "MIÉ", "JUE", "VIE", "SÁB"},
    {"DOM", "LUN", "MAR", "MER", "GIO", "VEN", "SAB"},
    {"ZO", "MA", "DI", "WO", "DO", "VR", "ZA"},
    {"PAZ", "PTS", "SAL", "ÇAR", "PER", "CUM", "CTS"},
    {"NE", "PO", "ÚT", "ST", "ČT", "PÁ", "SO"},
    {"DOM", "SEG", "TER", "QUA", "QUI", "SEX", "SÁB"},
    {"ΚΥΡ", "ΔΕΥ", "ΤΡΙ", "ΤΕΤ", "ΠΕΜ", "ΠΑΡ", "ΣΑΒ"},
    {"SÖN", "MÅN", "TIS", "ONS", "TOR", "FRE", "LÖR"},
    {"NDZ", "PON", "WTO", "ŚRO", "CZW", "PIĄ", "SOB"},
    {"NE", "PO", "UT", "ST", "ŠT", "PI", "SO"},
    {"CN", "T2", "T3", "T4", "T5", "T6", "T7"},
    {"DUM", "LUN", "MAR", "MIE", "JOI", "VIN", "SÂM"},
    {"DG", "DL", "DT", "DC", "DJ", "DV", "DS"},
    {"SØN", "MAN", "TIR", "ONS", "TOR", "FRE", "LØR"},
    {"ВС", "ПН", "ВТ", "СР", "ЧТ", "ПТ", "СБ"},
    {"P", "E", "T", "K", "N", "R", "L"},
    {"IG", "AL", "AR", "AZ", "OG", "OL", "LR"},
    {"SU", "MA", "TI", "KE", "TO", "PE", "LA"},
    {"SØN", "MAN", "TIR", "ONS", "TOR", "FRE", "LØR"},
    {"SEK", "PIR", "ANT", "TRE", "KET", "PEN", "ŠEŠ"},
    {"NED", "PON", "TOR", "SRE", "ČET", "PET", "SOB"},
    {"VAS", "HÉT", "KED", "SZE", "CSÜ", "PÉN", "SZO"},
    {"NED", "PON", "UTO", "SRE", "ČET", "PET", "SUB"},
    {"DOM", "LUA", "MÁI", "CÉA", "DÉA", "AOI", "SAT"},
    {"SVĒ", "PIR", "OTR", "TRE", "CET", "PIE", "SES"},
    {"NE", "PO", "UT", "SR", "ČE", "PE", "SU"},
    {"日", "一", "二", "三", "四", "五", "六"},
    {"MIN", "SEN", "SEL", "RAB", "KAM", "JUM", "SAB"},
    {"НД", "ПН", "ВТ", "СР", "ЧТ", "ПТ", "СБ"},
    {"SUL", "LLN", "MAW", "MER", "IAU", "GWE", "SAD"},
    {"DOM", "LUN", "MAR", "MER", "XOV", "VEN", "SAB"},
    {"日", "月", "火", "水", "木", "金", "土"},
    {"일", "월", "화", "수", "목", "금", "토"},
    {"א", "ב", "ג", "ד", "ה", "ו", "ש"},
    {"SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"}};

/* month names in many different languages! */
const char monthNames[38][12][8] = {
    {"JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT",
     "NOV", "DEC"},
    {"JAN", "FÉV", "MAR", "AVR", "MAI", "JUI", "JUL", "AOÛ", "SEP", "OCT",
     "NOV", "DÉC"},
    {"JAN", "FEB", "MÄR", "APR", "MAI", "JUN", "JUL", "AUG", "SEP", "OKT",
     "NOV", "DEZ"},
    {"ENE", "FEB", "MAR", "ABR", "MAY", "JUN", "JUL", "AGO", "SEP", "OCT",
     "NOV", "DIC"},
    {"GEN", "FEB", "MAR", "APR", "MAG", "GIU", "LUG", "AGO", "SET", "OTT",
     "NOV", "DIC"},
    {"JAN", "FEB", "MRT", "APR", "MEI", "JUN", "JUL", "AUG", "SEP", "OKT",
     "NOV", "DEC"},
    {"OCA", "ŞUB", "MAR", "NİS", "MAY", "HAZ", "TEM", "AĞU", "EYL", "EKİ",
     "KAS", "ARA"},
    {"LED", "ÚNO", "BŘE", "DUB", "KVĚ", "ČRV", "ČVC", "SRP", "ZÁŘ", "ŘÍJ",
     "LIS", "PRO"},
    {"JAN", "FEV", "MAR", "ABR", "MAI", "JUN", "JUL", "AGO", "SET", "OUT",
     "NOV", "DEZ"},
    {"ΙΑΝ", "ΦΕΒ", "ΜΑΡ", "ΑΠΡ", "ΜΑΪ", "ΙΟΝ", "ΙΟΛ", "ΑΥΓ", "ΣΕΠ", "ΟΚΤ",
     "ΝΟΕ", "ΔΕΚ"},
    {"JAN", "FEB", "MAR", "APR", "MAJ", "JUN", "JUL", "AUG", "SEP", "OKT",
     "NOV", "DEC"},
    {"STY", "LUT", "MAR", "KWI", "MAJ", "CZE", "LIP", "SIE", "WRZ", "PAŹ",
     "LIS", "GRU"},
    {"JAN", "FEB", "MAR", "APR", "MÁJ", "JÚN", "JÚL", "AUG", "SEP", "OKT",
     "NOV", "DEC"},
    {"Th1", "Th2", "Th3", "Th4", "Th5", "Th6", "Th7", "Th8", "Th9", "T10",
     "T11", "T12"},
    {"IAN", "FEB", "MAR", "APR", "MAI", "IUN", "IUL", "AUG", "SEP", "OCT",
     "NOI", "DEC"},
    {"GEN", "FEB", "MAR", "ABR", "MAI", "JUN", "JUL", "AGO", "SET", "OCT",
     "NOV", "DES"},
    {"JAN", "FEB", "MAR", "APR", "MAI", "JUN", "JUL", "AUG", "SEP", "OKT",
     "NOV", "DES"},
    {"ЯНВ", "ФЕВ", "МАР", "АПР", "МАЙ", "ИЮН", "ИЮЛ", "АВГ", "СЕН", "ОКТ",
     "НОЯ", "ДЕК"},
    {"JAN", "VEB", "MÄR", "APR", "MAI", "JUN", "JUL", "AUG", "SEP", "OKT",
     "NOV", "DET"},
    {"URT", "OTS", "MAR", "API", "MAI", "EKA", "UZT", "ABU", "IRA", "URR",
     "AZA", "ABE"},
    {"TAM", "HEL", "MAA", "HUH", "TOU", "KES", "HEI", "ELO", "SYY", "LOK",
     "MAR", "JOU"},
    {"JAN", "FEB", "MAR", "APR", "MAJ", "JUN", "JUL", "AUG", "SEP", "OKT",
     "NOV", "DEC"},
    {"SAU", "VAS", "KOV", "BAL", "GEG", "BIR", "LIE", "RUG", "RGS", "SPA",
     "LAP", "GRU"},
    {"JAN", "FEB", "MAR", "APR", "MAJ", "JUN", "JUL", "AVG", "SEP", "OKT",
     "NOV", "DEC"},
    {"JAN", "FEB", "MÁR", "ÁPR", "MÁJ", "JÚN", "JÚL", "AUG", "SZE", "OKT",
     "NOV", "DEC"},
    {"SIJ", "VEL", "OŽU", "TRA", "SVI", "LIP", "SRP", "KOL", "RUJ", "LIS",
     "STU", "PRO"},
    {"EAN", "FEA", "MÁR", "AIB", "BEA", "MEI", "IÚI", "LÚN", "MFÓ", "DFÓ",
     "SAM", "NOL"},
    {"JAN", "FEB", "MAR", "APR", "MAI", "JŪN", "JŪL", "AUG", "SEP", "OKT",
     "NOV", "DEC"},
    {"JAN", "FEB", "MAR", "APR", "MAJ", "JUN", "JUL", "AVG", "SEP", "OKT",
     "NOV", "DEC"},
    {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"},
    {"JAN", "FEB", "MAR", "APR", "MEI", "JUN", "JUL", "AGU", "SEP", "OKT",
     "NOV", "DES"},
    {"СІЧ", "ЛЮТ", "БЕР", "КВІ", "ТРА", "ЧЕР", "ЛИП", "СЕР", "ВЕР", "ЖОВ",
     "ЛИС", "ГРУ"},
    {"ION", "CHW", "MAW", "EBR", "MAI", "MEH", "GOR", "AWS", "MED", "HYD",
     "TCH", "RHA"},
    {"XAN", "FEB", "MAR", "ABR", "MAI", "XUÑ", "XUL", "AGO", "SET", "OUT",
     "NOV", "NAD"},
    {"1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月",
     "11月", "12月"},
    {"1월", "2월", "3월", "4월", "5월", "6월", "7월", "8월", "9월", "10월",
     "11월", "12월"},
    {"ינו", "פבר", "מרץ", "אפר", "מאי", "יונ", "יול", "אוג", "ספט", "אוק",
     "נוב", "דצמ"},
    {"JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT",
     "NOV", "DEC"}};

/* Per-language idiomatic date format string. Used by widgets.c to expand the
   {local_date} super-token at render time. Mirrored in
   config-page/src/data/dateFormats.ts (preview only) — keep both in sync. */
const char *const defaultDateFormat[38] = {
    /*  0 en-us */ "{day_name}, {month_name} {day0}",
    /*  1 fr-fr */ "{day_name} {day0} {month_name}",
    /*  2 de-de */ "{day_name}, {day0}. {month_name}",
    /*  3 es-es */ "{day_name} {day0} {month_name}",
    /*  4 it-it */ "{day_name} {day0} {month_name}",
    /*  5 nl-nl */ "{day_name} {day0} {month_name}",
    /*  6 tr-tr */ "{day0} {month_name} {day_name}",
    /*  7 cs-cz */ "{day_name} {day0}. {month_name}",
    /*  8 pt-pt */ "{day_name}, {day0} {month_name}",
    /*  9 el-gr */ "{day_name}, {day0} {month_name}",
    /* 10 sv-se */ "{day_name} {day0} {month_name}",
    /* 11 pl-pl */ "{day_name}, {day0} {month_name}",
    /* 12 sk-sk */ "{day_name} {day0}. {month_name}",
    /* 13 vi-vn */ "{day_name}, {day0}/{month_num}",
    /* 14 ro-ro */ "{day_name}, {day0} {month_name}",
    /* 15 ca-es */ "{day_name} {day0} {month_name}",
    /* 16 nb-no */ "{day_name} {day0}. {month_name}",
    /* 17 ru-ru */ "{day_name}, {day0} {month_name}",
    /* 18 et-ee */ "{day_name}, {day0}. {month_name}",
    /* 19 eu-es */ "{day_name} {day0} {month_name}",
    /* 20 fi-fi */ "{day_name} {day0}. {month_name}",
    /* 21 da-dk */ "{day_name} {day0}. {month_name}",
    /* 22 lt-lt */ "{day_name}, {day0} {month_name}",
    /* 23 sl-si */ "{day_name}, {day0}. {month_name}",
    /* 24 hu-hu */ "{month_name} {day0}., {day_name}",
    /* 25 hr-hr */ "{day_name}, {day0}. {month_name}",
    /* 26 ga-ie */ "{day_name} {day0} {month_name}",
    /* 27 lv-lv */ "{day_name}, {day0}. {month_name}",
    /* 28 sr-rs */ "{day_name}, {day0}. {month_name}",
    /* 29 zh-cn */ "{month_num}月{day}日 {day_name}",
    /* 30 id-id */ "{day_name}, {day0} {month_name}",
    /* 31 uk-ua */ "{day_name}, {day0} {month_name}",
    /* 32 cy-gb */ "{day_name} {day0} {month_name}",
    /* 33 gl-es */ "{day_name} {day0} {month_name}",
    /* 34 ja-jp */ "{month_num}月{day}日 ({day_name})",
    /* 35 ko-kr */ "{month_num}월 {day}일 ({day_name})",
    /* 36 he-il */ "{day_name} {day0} {month_name}",
    /* 37 en-gb */ "{day_name}, {day0} {month_name}"};

/* Per-language decimal separator. Most European languages use ',';
   English, Asian languages, Irish, Welsh, Hebrew use '.'. */
const char decimalSeparator[38] = {
    /*  0 en-us */ '.', /*  1 fr-fr */ ',', /*  2 de-de */ ',', /*  3 es-es */ ',',
    /*  4 it-it */ ',', /*  5 nl-nl */ ',', /*  6 tr-tr */ ',', /*  7 cs-cz */ ',',
    /*  8 pt-pt */ ',', /*  9 el-gr */ ',', /* 10 sv-se */ ',', /* 11 pl-pl */ ',',
    /* 12 sk-sk */ ',', /* 13 vi-vn */ ',', /* 14 ro-ro */ ',', /* 15 ca-es */ ',',
    /* 16 nb-no */ ',', /* 17 ru-ru */ ',', /* 18 et-ee */ ',', /* 19 eu-es */ ',',
    /* 20 fi-fi */ ',', /* 21 da-dk */ ',', /* 22 lt-lt */ ',', /* 23 sl-si */ ',',
    /* 24 hu-hu */ ',', /* 25 hr-hr */ ',', /* 26 ga-ie */ '.', /* 27 lv-lv */ ',',
    /* 28 sr-rs */ ',', /* 29 zh-cn */ '.', /* 30 id-id */ ',', /* 31 uk-ua */ ',',
    /* 32 cy-gb */ '.', /* 33 gl-es */ ',', /* 34 ja-jp */ '.', /* 35 ko-kr */ '.',
    /* 36 he-il */ '.', /* 37 en-gb */ '.'};

