#pragma once

#include <pebble.h>

// Define all the "true" metrics for the various fonts we're using
// "Height" is the actual mesured pixel height from the top to the baseline
// "Offset" is the empty space between where you ask graphics_draw_text
// to draw and where it actually draws

// leco
#define METRIC_LECO_32_BOLD_NUMBERS_HEIGHT 22
#define METRIC_LECO_32_BOLD_NUMBERS_OFFSET 10

#define METRIC_LECO_36_BOLD_NUMBERS_HEIGHT 25
#define METRIC_LECO_36_BOLD_NUMBERS_OFFSET 11

#define METRIC_LECO_38_BOLD_NUMBERS_HEIGHT 27
#define METRIC_LECO_38_BOLD_NUMBERS_OFFSET 11

#define METRIC_LECO_42_NUMBERS_HEIGHT 29
#define METRIC_LECO_42_NUMBERS_OFFSET 13

#define METRIC_LECO_60_NUMBERS_HEIGHT 42
#define METRIC_LECO_60_NUMBERS_OFFSET 18

// gothic
#define METRIC_GOTHIC_14_HEIGHT 8
#define METRIC_GOTHIC_14_OFFSET 6

#define METRIC_GOTHIC_18_HEIGHT 11
#define METRIC_GOTHIC_18_OFFSET 7

#define METRIC_GOTHIC_24_HEIGHT 14
#define METRIC_GOTHIC_24_OFFSET 10

#define METRIC_GOTHIC_28_HEIGHT 18
#define METRIC_GOTHIC_28_OFFSET 10

// Choose our fonts/metrics based on platform

// ****** Pebble Time 2 ******
#if defined(PBL_PLATFORM_EMERY)
#define LINE_PADDING 13

#define FONT_TIME FONT_KEY_LECO_42_NUMBERS
#define FONT_TIME_HEIGHT METRIC_LECO_42_NUMBERS_HEIGHT
#define FONT_TIME_OFFSET METRIC_LECO_42_NUMBERS_OFFSET

#define FONT_WIDGET_PRIMARY FONT_KEY_GOTHIC_24_BOLD
#define FONT_WIDGET_PRIMARY_HEIGHT METRIC_GOTHIC_24_HEIGHT
#define FONT_WIDGET_PRIMARY_OFFSET METRIC_GOTHIC_24_OFFSET

#define FONT_WIDGET_SECONDARY FONT_KEY_GOTHIC_18
#define FONT_WIDGET_SECONDARY_HEIGHT METRIC_GOTHIC_18_HEIGHT
#define FONT_WIDGET_SECONDARY_OFFSET METRIC_GOTHIC_18_OFFSET

#define FONT_WIDGET_PRIMARY_LARGE FONT_KEY_GOTHIC_28_BOLD
#define FONT_WIDGET_PRIMARY_LARGE_HEIGHT METRIC_GOTHIC_28_HEIGHT
#define FONT_WIDGET_PRIMARY_LARGE_OFFSET METRIC_GOTHIC_28_OFFSET

#define FONT_WIDGET_SECONDARY_LARGE FONT_KEY_GOTHIC_24
#define FONT_WIDGET_SECONDARY_LARGE_HEIGHT METRIC_GOTHIC_24_HEIGHT
#define FONT_WIDGET_SECONDARY_LARGE_OFFSET METRIC_GOTHIC_24_OFFSET

// ****** Pebble Round 2 ******
#elif defined(PBL_PLATFORM_GABBRO)

#define LINE_PADDING 13

#define FONT_TIME FONT_KEY_LECO_60_NUMBERS_AM_PM
#define FONT_TIME_HEIGHT METRIC_LECO_60_NUMBERS_HEIGHT
#define FONT_TIME_OFFSET METRIC_LECO_60_NUMBERS_OFFSET

#define FONT_WIDGET_PRIMARY FONT_KEY_GOTHIC_24_BOLD
#define FONT_WIDGET_PRIMARY_HEIGHT METRIC_GOTHIC_24_HEIGHT
#define FONT_WIDGET_PRIMARY_OFFSET METRIC_GOTHIC_24_OFFSET

#define FONT_WIDGET_SECONDARY FONT_KEY_GOTHIC_18
#define FONT_WIDGET_SECONDARY_HEIGHT METRIC_GOTHIC_18_HEIGHT
#define FONT_WIDGET_SECONDARY_OFFSET METRIC_GOTHIC_18_OFFSET

#define FONT_WIDGET_PRIMARY_LARGE FONT_KEY_GOTHIC_28_BOLD
#define FONT_WIDGET_PRIMARY_LARGE_HEIGHT METRIC_GOTHIC_28_HEIGHT
#define FONT_WIDGET_PRIMARY_LARGE_OFFSET METRIC_GOTHIC_28_OFFSET

#define FONT_WIDGET_SECONDARY_LARGE FONT_KEY_GOTHIC_24
#define FONT_WIDGET_SECONDARY_LARGE_HEIGHT METRIC_GOTHIC_24_HEIGHT
#define FONT_WIDGET_SECONDARY_LARGE_OFFSET METRIC_GOTHIC_24_OFFSET

// ****** Pebble Time Round ******
#elif defined(PBL_PLATFORM_CHALK)
#define LINE_PADDING 8

#define FONT_TIME FONT_KEY_LECO_42_NUMBERS
#define FONT_TIME_HEIGHT METRIC_LECO_42_NUMBERS_HEIGHT
#define FONT_TIME_OFFSET METRIC_LECO_42_NUMBERS_OFFSET

#define FONT_WIDGET_PRIMARY FONT_KEY_GOTHIC_18_BOLD
#define FONT_WIDGET_PRIMARY_HEIGHT METRIC_GOTHIC_18_HEIGHT
#define FONT_WIDGET_PRIMARY_OFFSET METRIC_GOTHIC_18_OFFSET

#define FONT_WIDGET_SECONDARY FONT_KEY_GOTHIC_14
#define FONT_WIDGET_SECONDARY_HEIGHT METRIC_GOTHIC_14_HEIGHT
#define FONT_WIDGET_SECONDARY_OFFSET METRIC_GOTHIC_14_OFFSET

#define FONT_WIDGET_PRIMARY_LARGE FONT_KEY_GOTHIC_24_BOLD
#define FONT_WIDGET_PRIMARY_LARGE_HEIGHT METRIC_GOTHIC_24_HEIGHT
#define FONT_WIDGET_PRIMARY_LARGE_OFFSET METRIC_GOTHIC_24_OFFSET

#define FONT_WIDGET_SECONDARY_LARGE FONT_KEY_GOTHIC_18
#define FONT_WIDGET_SECONDARY_LARGE_HEIGHT METRIC_GOTHIC_18_HEIGHT
#define FONT_WIDGET_SECONDARY_LARGE_OFFSET METRIC_GOTHIC_18_OFFSET

// Everyone else (OG Pebble, Pebble Time, Pebble 2)
#else
#define LINE_PADDING 8

#define FONT_TIME FONT_KEY_LECO_32_BOLD_NUMBERS
#define FONT_TIME_HEIGHT METRIC_LECO_32_BOLD_NUMBERS_HEIGHT
#define FONT_TIME_OFFSET METRIC_LECO_32_BOLD_NUMBERS_OFFSET

#define FONT_WIDGET_PRIMARY FONT_KEY_GOTHIC_18_BOLD
#define FONT_WIDGET_PRIMARY_HEIGHT METRIC_GOTHIC_18_HEIGHT
#define FONT_WIDGET_PRIMARY_OFFSET METRIC_GOTHIC_18_OFFSET

#define FONT_WIDGET_SECONDARY FONT_KEY_GOTHIC_14
#define FONT_WIDGET_SECONDARY_HEIGHT METRIC_GOTHIC_14_HEIGHT
#define FONT_WIDGET_SECONDARY_OFFSET METRIC_GOTHIC_14_OFFSET

#define FONT_WIDGET_PRIMARY_LARGE FONT_KEY_GOTHIC_24_BOLD
#define FONT_WIDGET_PRIMARY_LARGE_HEIGHT METRIC_GOTHIC_24_HEIGHT
#define FONT_WIDGET_PRIMARY_LARGE_OFFSET METRIC_GOTHIC_24_OFFSET

#define FONT_WIDGET_SECONDARY_LARGE FONT_KEY_GOTHIC_18
#define FONT_WIDGET_SECONDARY_LARGE_HEIGHT METRIC_GOTHIC_18_HEIGHT
#define FONT_WIDGET_SECONDARY_LARGE_OFFSET METRIC_GOTHIC_18_OFFSET
#endif
